### PR TITLE
fix: correctly handle peer conflicts between peers

### PR DESCRIPTION
**Pull request by nlf**
this corrects the case where a project has dependencies that have peer dependencies with different, yet overlapping required ranges such that we correctly identify the resolved version that matches as many needs as possible.

## References

closes npm/cli#2553
closes npm/cli#2999
closes npm/cli#3083

### CODE REVIEW

**Comment by nlf** [comment]
the two failing runs were transient failures during the tests, socket timeouts. since only one event failed while the other passed for the two that failed, this seems safe to ignore.

**Comment by princemaple** [comment]
Is this in npm 7.11.1? I just updated to this version and `ng update` still getting errors.

**Comment by princemaple** [comment]
thanks for the confirmation @talsi

**Comment by rarkins** [comment]
@talsi is there any new or reopened issue to track this? Perhaps best for you to do it as you have a nice clean reproduction?

**Comment by talsi** [comment]
@rarkins i waiting for https://github.com/npm/cli/issues/2553 to reopen

**Pull request closed without merging**
