### PR TITLE
chore: remove some unused lines on tests

### PR DESCRIPTION
**Pull request by ruyadorno**
Was almost pushing this as part of the other fixes but I feel there's a big chance this is going to be one of these times @isaacs says "oh no, these were actually there for a reason" so a sep PR makes it simpler to just ignore it if that's the case 😄

### CODE REVIEW

**Comment by isaacs** [comment]
LGTM.  Maybe we should lint our tests, too?  I usually don't, because occasionally tests have to do some unsavory things.

**Comment by ljharb** [comment]
Yes, always :-) you can use “overrides” if you need tweaked rules for the tests, as well as override comments.

**Comment by isaacs** [comment]
@ljharb idk, the override we have in place right now is pretty effective.

**Comment by ljharb** [comment]
i took your previous comment as an implication that tests are not linted at all, so you mean, the override that tests aren't linted at all? :-)

**Pull request closed without merging**
